name: Python sample CI

on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.9'

      - name: install other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: run test
        run: |
          pytest
    




